# -*- python -*-
Import('env')

lib = env.StaticLibrary('lib', ['Alu.cpp', 'Ram.cpp', 'Parser.cpp', 'Instruction.cpp', 'Cu.cpp', 'Fifo.cpp'])

if not env['debug']:
    env.BoostTests(Glob('tests/*.cpp'), lib)

p = env.Program('core-war', ['main.cpp'] ,LIBS=[lib])

Return('p')
