# -*- python -*-
Import('env')

lib = env.StaticLibrary('lib', ['Alu.cpp', 'Ram.cpp', 'Parser.cpp', 'Instruction.cpp'])

env.BoostTests(Glob('tests/*.cpp'), lib)

p = env.Program('core-war', ['main.cpp'] ,LIBS=[lib])

Return('p')
